### ISSUE TITLE
long shot - question

### ISSUE THREAD

**Issue by SteveTapajna** [alvsanand/liquibase-athena#3]
hey, I was using liquibase in an HDFS env (overtop of Impala) and Liquibase didn't know how to create tables there, but once I created the databasechangelog table in the schema, it was good to go.  However, now I'm looking at Athena, and again, the create table format is not what liquibase expects.  I've created one in my schema, but Liquibase never seems to see it because it always tries to create it and fails.  I can't seem to find any combimation of schema or catalog properties that will get it to work.  Was that your experience as well?

Thanks,

Steve

**Comment by alvsanand** [comment]
Exactly. I could not find any extension that could work for AWS Athena and that is why I created this connector.  In any extension, you must specify which commands or data types supports, how to create the changelog tables, etc. I made the best to customize it for Athena but I am not an expert of Liquibase.

However, I am already using in my company and it seems to work quite well.
